name: Build and Push Docker Image

on:
  push:
    branches: [ dev ]  # Trigger workflow on dev branch
  pull_request:
    branches: [ dev ]  # Trigger on PRs to dev branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev  # Explicitly checkout dev branch
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_OUTPUT
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: DockerFile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:${{ steps.timestamp.outputs.TIMESTAMP }}
            ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:latest
